// <auto-generated />
using System;
using MVC_crud_sonu_.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_crud_sonu_.Migrations
{
    [DbContext(typeof(AnimaMvcContext))]
    [Migration("20230315130618_added-two-more-tables")]
    partial class addedtwomoretables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_crud_sonu_.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("MVC_crud_sonu_.Models.GuestServiceAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceAgentAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceAgentBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceAgentFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceAgentLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GuestServiceAgent");
                });

            modelBuilder.Entity("MVC_crud_sonu_.Models.Zookeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ZookeeperAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZookeeperBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZookeeperFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZookeeperLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zookeeper");
                });
#pragma warning restore 612, 618
        }
    }
}
